import {TagsIcon} from '@sanity/icons'
import {defineType, defineField, defineArrayMember} from 'sanity'

export const familyType = defineType({
  name: 'family',
  title: 'Collection',
  type: 'document',
  icon: TagsIcon,
  fields: [
    defineField({
      name: 'title',
      title: 'Collection Name',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 4,
      description: 'Editorial collection copy for collection landing pages.',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'image',
      options: {hotspot: true},
      fields: [
        defineField({
          name: 'alt',
          title: 'Alternative Text',
          type: 'string',
        }),
      ],
    }),
    defineField({
      name: 'heroImageUrl',
      title: 'Hero Image URL (external)',
      type: 'url',
      readOnly: true,
      description: 'Local migration bridge for existing collection hero imagery before Sanity assets are uploaded.',
    }),
    defineField({
      name: 'productCount',
      title: 'Product Count',
      type: 'number',
      readOnly: true,
      description: 'Generated by migration scripts for inventory validation.',
    }),
    defineField({
      name: 'productTypes',
      title: 'Product Types',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      readOnly: true,
    }),
    defineField({
      name: 'sourceValues',
      title: 'Source Values',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      readOnly: true,
      description: 'Raw WordPress category/title signals that resolved to this collection.',
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'object',
      fields: [
        defineField({name: 'title', title: 'Title', type: 'string'}),
        defineField({name: 'description', title: 'Description', type: 'text', rows: 3}),
      ],
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'productCount',
      media: 'heroImage',
    },
    prepare(selection) {
      return {
        title: selection.title,
        subtitle: selection.subtitle ? `${selection.subtitle} products` : undefined,
        media: selection.media,
      }
    },
  },
})
