import {TrolleyIcon} from '@sanity/icons/Trolley'
import {defineType, defineField, defineArrayMember} from 'sanity'

export const productCategoryType = defineType({
  name: 'productCategory',
  title: 'Product Category',
  type: 'document',
  icon: TrolleyIcon,
  fields: [
    defineField({
      name: 'title',
      title: 'Category Name',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'order',
      title: 'Navigation Order',
      type: 'number',
    }),
    defineField({
      name: 'isPrimaryNavigation',
      title: 'Show In Primary Catalog Navigation',
      type: 'boolean',
      initialValue: true,
    }),
    defineField({
      name: 'productCount',
      title: 'Product Count',
      type: 'number',
      readOnly: true,
      description: 'Generated by migration scripts for inventory validation.',
    }),
    defineField({
      name: 'sourceValues',
      title: 'Source Values',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      readOnly: true,
      description: 'Raw category labels that normalize into this product category.',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'productCount',
    },
    prepare(selection) {
      return {
        title: selection.title,
        subtitle: selection.subtitle ? `${selection.subtitle} products` : undefined,
      }
    },
  },
})
